### ISSUE TITLE
Remove pre-allocated titles from full Landonline title table

### ISSUE THREAD

**Issue by palmerj** [linz/linz-lds-bde-schema#15]
Currently pre-allocated titles are included in the full landonline titles table on LDS: https://data.linz.govt.nz/table/2067-landonline-title/

Pending titles are not released so for users of the changesets they get the new pre-allocated title as an insert, then when it moves to pending it comes through as a delete, only to turn up again as an insert once it’s moved past pending status.
The Property Rights team say pre-allocated titles have no value to LDS users.

To filter them out the tmp_excluded_titles table where clause would change to include status='PREA':
CREATE TEMP TABLE tmp_excluded_titles AS
SELECT
TTL.title_no
FROM
crs_title TTL
WHERE
TTL.status = 'PEND' AND TTL.status = 'PREA'
UNION
SELECT
title_no
FROM
tmp_training_titles;

**Comment by palmerj** [comment]
Moved from https://github.com/linz/linz_bde_uploader/issues/42

**Comment by strk** [comment]
is it ok to postpone this to 1.2.0 or is it urgent ?

**Comment by strk** [comment]
btw, your suggested condition would be always false: ``` TTL.status = 'PEND' AND TTL.status = 'PREA'```
I guess you meant ```OR``` there ?

**Comment by strk** [comment]
I've prepared a PR for this: #63

**Comment by palmerj** [comment]
@iharrison raised this issue. But looks like OR is required.

**Comment by palmerj** [comment]
@iharrison Do we think we need to remove pre-allocated titles because the audit_id changes from pre-allocated to pend?  But the original reason to keep them was that survey plans usally pre-allocate the titles and were always know on survey plan deposit (which is public approved info). But I do think it's ok to remove, unless some surveyor or lawyers software packages are somehow using this data downstream. Make me wonder the best way to deal with remove public data...

**Comment by iharrison** [comment]
Excuse the spam but here's the original email chain discussing this. See my summary of the issue in the first email.

From: Brian Evans 
Sent: Saturday, 8 October 2016 12:18 p.m.
To: Ian Harrison
Cc: Bill M. Nelson
Subject: Re: Pre-allocated titles

They only have a use for the surveyor or conveyancer who has requested the preallocation, and anyone they supply that reference to. In some cases the proposed title may not actually be created due to changing circumstances. If a third party is provided a pre-allocated title number it is simply so they have an advanced link to it in their relevant records pending creation of the title, so effectively the only ones who are likely to have a use for it will already have it.

So short answer is no value to LDS users.


On Fri, Oct 7, 2016 at 2:06 PM +1300, "Ian Harrison" <iharrison@linz.govt.nz> wrote:
Hi Brian,

Currently pre-allocated titles are included in the full landonline titles table on LDS: https://data.linz.govt.nz/table/2067-landonline-title/
As I’ve described below pending titles are not released so for users of the changesets they get the new pre-allocated title as an insert, then when it moves to pending it comes through as a delete, only to turn up again as an insert once it’s moved past pending status. As a result we’re thinking it’s probably best to exclude pre-allocated titles.
What do you think?
Do you think pre-allocated titles are useful for anyone out there?

Cheers,
Ian.

From: Bill M. Nelson 
Sent: Thursday, 6 October 2016 4:28 p.m.
To: Ian Harrison
Subject: RE: Pre-allocated titles

Yeah. We release the pending titles/parcels for TAs only at the moment. So we probably should remove the preallocated titles. Do they have a code or something that makes them easy to identify?

Can you add all the details as a new github issue. And maybe double check with Brian on the approach? We’ve got a couple of issues backed up for the next LOL release anyway. Could do all this at once.

https://github.com/linz/linz_bde_uploader/issues

Cheers,

Bill

From: Ian Harrison 
Sent: Thursday, 6 October 2016 4:18 p.m.
To: Bill M. Nelson
Subject: Pre-allocated titles

Hi Bill,

Lubo noticed titles are being deleted and then inserted again later in the changesets.
I had a look and we currently release pre-allocated titles. These progress to pending titles which we don't release. And then on to the next status (live I think). In the changesets the result is a title is inserted (pre-allocated), deleted (pending) and then inserted again (live).
Not a big deal but a little messy for users.
Would it be better if we didn’t release pre-allocated titles? I guess some users do find them useful but don’t know.
Lubo suggested releasing the pending titles with the details removed but I don’t think Ron’s team would be happy with this idea.

Cheers,
Ian.
